version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/oshou/go-gcp-sample
    steps:
      - checkout
      - run: go vet -v -t -d ./...
      - run: go test -v ./...
